export const SET_CARDS_DATA = "SET_CARDS_DATA";
export const FULL_ADDON_PAGE_DATA_LOADED = "FULL_ADDON_PAGE_DATA_LOADED";
export const FULL_ADDON_TYPES = "FULL_ADDON_TYPES";
export const TOTAL_PAGES = "TOTAL_PAGES";
export const ALL_CARDS = "ALL_CARDS";
