trigger:
    branches:
        include:
            - dev/*
            - master
            - stage/*
    #paths:
    #  include:
    #    - Src/UDS.Portal.Api/*

pool:
  vmImage: 'windows-latest'

variables:
  ${{ if startsWith(variables['Build.SourceBranchName'], 'dev/') }}: 
    command: 'npm run-script build-prod'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    command: 'npm run-script build-stage'
  ${{ if startsWith(variables['Build.SourceBranchName'], 'stage/') }}:
    command: 'npm run-script build-stage'

steps:
- checkout: self
  submodules: true

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)'
  displayName: "NPM Install"

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: '${{variables.command}}'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Src\UDS.Portal.Api\bin\Debug\netcoreapp5.0\UDS.Portal.Api.dll'
    ArtifactName: 'drop'
    publishLocation: 'Container'

