trigger:
    branches:
        include:
            - dev/*
            - master
            - stage/*
    #paths:
    #  include:
    #    - Src/UDS.Portal.Api/*

pool:
  vmImage: 'windows-latest'

variables:
  - name: system.debug
    value: 'true' 
  - name: command
    ${{ if startsWith(variables['Build.SourceBranchName'], 'dev/') }}: 
      command: "run-script build-prod"
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      command: "run-script build-dev"
    ${{ if startsWith(variables['Build.SourceBranchName'], 'stage/') }}:
      command: "run-script build-stage"

stages:
  - stage: buildSoution
    displayName: Build Solution
    jobs:
      - job: Checkout
        displayName: Checkout self, with submodules
        steps:
        - checkout: self
          submodules: true

      - job: NodeTool
        displayName: Install Node 12.x
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'

      - job: NpmCleanCache
        displayName: Clean NPM cache
        steps:
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: 'cache clean --force'

      - job: NpmInstall
        displayName: NPM install
        steps:
        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customRegistry: 'useFeed'
            customFeed: '9df1d1b4-3153-4acf-a38f-98ad42ca09b5'
          displayName: "NPM Install"

      - job: NpmBuild
        displayName: NPM build solution for environment
        steps:
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: '${{ variables.command }}'
            customRegistry: 'useFeed'
            customFeed: '9df1d1b4-3153-4acf-a38f-98ad42ca09b5'
          displayName: "NPM Run"

      - job: PublishArtifactToDrop
        displayName: Publish artifacts to drop
        steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)\src'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: "Publish artifacts to drop"

