trigger:
    branches:
        include:
            - dev/*
            - master
            - stage/*
    #paths:
    #  include:
    #    - Src/UDS.Portal.Api/*

pool:
  vmImage: 'windows-latest'

variables:
  - name: system.debug
    value: 'true' 
  - name: command
    ${{ if startsWith(variables['Build.SourceBranchName'], 'dev/') }}: 
      value: 'run-script build-prod'
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: 'run-script build-stage'
    ${{ if startsWith(variables['Build.SourceBranchName'], 'stage/') }}:
      value: 'run-script build-stage'

steps:
- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: 'cache clean --force'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customRegistry: 'useFeed'
    customFeed: '9df1d1b4-3153-4acf-a38f-98ad42ca09b5'
  displayName: "NPM Install"

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: 'run-script build-stage'
    customRegistry: 'useFeed'
    customFeed: '9df1d1b4-3153-4acf-a38f-98ad42ca09b5'
  displayName: "NPM Run"


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)\UDS-Portal-API\Src\UDS.Portal.Api\wwwroot'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: "Publish artifacts to drop"

