trigger:
    branches:
        include:
            - dev/*
            - master
            - stage/*
    #paths:
    #  include:
    #    - Src/UDS.Portal.Api/*

pool:
  vmImage: 'windows-latest'

variables:
  - name: command
    ${{ if startsWith(variables['Build.SourceBranchName'], 'dev/') }}: 
      value: 'npm run-script build-prod'
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: 'npm run-script build-stage'
    ${{ if startsWith(variables['Build.SourceBranchName'], 'stage/') }}:
      value: 'npm run-script build-stage'

steps:
  - bash: |
       echo $(command)
#steps:
#- checkout: self
#  submodules: true
#
#- task: Npm@1
#  inputs:
#    command: 'install'
#    workingDir: '$(System.DefaultWorkingDirectory)'
#  displayName: "NPM Install"
#
#- task: Npm@1
#  inputs:
#    command: 'custom'
#    workingDir: '$(System.DefaultWorkingDirectory)'
#    customCommand: '${{variables.command}}'
#  displayName: "NPM Run"
#
#
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: 'Src\UDS.Portal.Api\bin\Debug\netcoreapp5.0\UDS.Portal.Api.dll'
#    ArtifactName: 'drop'
#    publishLocation: 'Container'
#  displayName: "Publish artifacts to drop"

