trigger:
    branches:
        include:
            - dev/*
            - master
            - stage/*
    #paths:
    #  include:
    #    - Src/UDS.Portal.Api/*



pool:
  vmImage: 'windows-latest'

variables:
- name: system.debug
  value: 'true' 
- name: command
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/dev/') }}:
   value: 'run-script build-dev'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}: 
   value: 'run-script build-prod'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/stage/') }}: 
   value: 'run-script build-stage'
- name: dropName
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/dev/') }}:
   value: 'SPA-dev'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}: 
   value: 'SPA-prod'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/stage/') }}: 
   value: 'SPA-stage'

stages:
  - stage: buildSoution
    displayName: Build Solution
    jobs:
      - job: BuildPortalSPA
        displayName: Build Portal SPA
        steps:
        - checkout: self
          submodules: true
          displayName: Checkout self, with submodules

        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'
          displayName: Install Node 12.x

        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: 'cache clean --force'
          displayName: Clean NPM cache

        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customRegistry: 'useFeed'
            customFeed: '9df1d1b4-3153-4acf-a38f-98ad42ca09b5'
          displayName: "NPM Install"

        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: '${{ variables.command }}'
            customRegistry: 'useFeed'
            customFeed: '9df1d1b4-3153-4acf-a38f-98ad42ca09b5'
          displayName: "NPM Run"

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)\src'
            ArtifactName: '${{variables.dropName}}'
            publishLocation: 'Container'
          displayName: "Publish artifacts to drop"
